# Generated by Django 4.0.7 on 2025-11-24 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(help_text='A unique identifier used for user login. Must be unique across all users.', max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, help_text="The user's given name. Used for personalization and identification.", max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text="The user's family name or surname. Helps distinguish users with similar first names.", max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time when the user account was created. Useful for tracking account age.', verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the user account is currently active and allowed to log in.', verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user has staff privileges, granting access to administrative features.', verbose_name='is staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
