# Generated by Django 5.2.5 on 2025-11-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Its show that this user is admin or not', verbose_name='is admin'),
        ),
    ]
